services:
  db:
    image: postgres:17
    container_name: "movie-rsvp-db"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=admin123"
      - "POSTGRES_DB=movie_rsvp"
    ports:
      - "5000:5432"
    volumes:
      - movie_rsvp_path:/var/lib/postgresql/data

volumes:
  movie_rsvp_path:
